server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iran_war_db
    username: iran
    password: iran
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
