server:
  port: 8383
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iran_war_db
    username: iran
    password: iran
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true

logging:
  level:
    org.springframework.security: INFO
